/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * OpenAPI spec version: 6.8.0.20190731.002
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.api;

import com.github.GBSEcom.client.ApiException;
import com.github.GBSEcom.model.CardVerificationRequest;
import com.github.GBSEcom.model.ErrorResponse;
import com.github.GBSEcom.model.TransactionResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CardVerificationApi
 */
@Ignore
public class CardVerificationApiTest {

    private final CardVerificationApi api = new CardVerificationApi();

    
    /**
     * Verify a payment card.
     *
     * Use this to perform card verification for a payment card.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyCardTest() throws ApiException {
        String contentType = null;
        String clientRequestId = null;
        String apiKey = null;
        Long timestamp = null;
        CardVerificationRequest cardVerificationRequest = null;
        String messageSignature = null;
        String region = null;
        TransactionResponse response = api.verifyCard(contentType, clientRequestId, apiKey, timestamp, cardVerificationRequest, messageSignature, region);

        // TODO: test validations
    }
    
}
