/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.5.0.20211029.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.github.GBSEcom.model.Option;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BasketItem
 */
public class BasketItemTest {
    private final BasketItem model = new BasketItem();

    /**
     * Model tests for BasketItem
     */
    @Test
    public void testBasketItem() {
        // TODO: test BasketItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'subTotal'
     */
    @Test
    public void subTotalTest() {
        // TODO: test subTotal
    }

    /**
     * Test the property 'valueAddedTax'
     */
    @Test
    public void valueAddedTaxTest() {
        // TODO: test valueAddedTax
    }

    /**
     * Test the property 'localTax'
     */
    @Test
    public void localTaxTest() {
        // TODO: test localTax
    }

    /**
     * Test the property 'deliveryAmount'
     */
    @Test
    public void deliveryAmountTest() {
        // TODO: test deliveryAmount
    }

    /**
     * Test the property 'chargeTotal'
     */
    @Test
    public void chargeTotalTest() {
        // TODO: test chargeTotal
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'detailedCategory'
     */
    @Test
    public void detailedCategoryTest() {
        // TODO: test detailedCategory
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

}
