/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.4.0.20210824.002
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ChinaDomestic
 */
public class ChinaDomesticTest {
    private final ChinaDomestic model = new ChinaDomestic();

    /**
     * Model tests for ChinaDomestic
     */
    @Test
    public void testChinaDomestic() {
        // TODO: test ChinaDomestic
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'productQuantity'
     */
    @Test
    public void productQuantityTest() {
        // TODO: test productQuantity
    }

    /**
     * Test the property 'productPrice'
     */
    @Test
    public void productPriceTest() {
        // TODO: test productPrice
    }

    /**
     * Test the property 'productDescription'
     */
    @Test
    public void productDescriptionTest() {
        // TODO: test productDescription
    }

    /**
     * Test the property 'redirectURL'
     */
    @Test
    public void redirectURLTest() {
        // TODO: test redirectURL
    }

    /**
     * Test the property 'limitCardFunctionToDebit'
     */
    @Test
    public void limitCardFunctionToDebitTest() {
        // TODO: test limitCardFunctionToDebit
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'bankId'
     */
    @Test
    public void bankIdTest() {
        // TODO: test bankId
    }

    /**
     * Test the property 'openId'
     */
    @Test
    public void openIdTest() {
        // TODO: test openId
    }

}
