/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.3.0.20210608.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.github.GBSEcom.model.ReceiverInfo;
import com.github.GBSEcom.model.SenderInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Disbursement
 */
public class DisbursementTest {
    private final Disbursement model = new Disbursement();

    /**
     * Model tests for Disbursement
     */
    @Test
    public void testDisbursement() {
        // TODO: test Disbursement
    }

    /**
     * Test the property 'disbursementType'
     */
    @Test
    public void disbursementTypeTest() {
        // TODO: test disbursementType
    }

    /**
     * Test the property 'senderInfo'
     */
    @Test
    public void senderInfoTest() {
        // TODO: test senderInfo
    }

    /**
     * Test the property 'receiverInfo'
     */
    @Test
    public void receiverInfoTest() {
        // TODO: test receiverInfo
    }

}
