/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.11.0.20200423.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Items
 */
public class ItemsTest {
    private final Items model = new Items();

    /**
     * Model tests for Items
     */
    @Test
    public void testItems() {
        // TODO: test Items
    }

    /**
     * Test the property 'networkType'
     */
    @Test
    public void networkTypeTest() {
        // TODO: test networkType
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'carrierName'
     */
    @Test
    public void carrierNameTest() {
        // TODO: test carrierName
    }

    /**
     * Test the property 'mobileCountryCode'
     */
    @Test
    public void mobileCountryCodeTest() {
        // TODO: test mobileCountryCode
    }

    /**
     * Test the property 'mobileNetworkCode'
     */
    @Test
    public void mobileNetworkCodeTest() {
        // TODO: test mobileNetworkCode
    }

    /**
     * Test the property 'subscriptionIdentificationNumber'
     */
    @Test
    public void subscriptionIdentificationNumberTest() {
        // TODO: test subscriptionIdentificationNumber
    }

    /**
     * Test the property 'locationAreaCode'
     */
    @Test
    public void locationAreaCodeTest() {
        // TODO: test locationAreaCode
    }

    /**
     * Test the property 'cellId'
     */
    @Test
    public void cellIdTest() {
        // TODO: test cellId
    }

    /**
     * Test the property 'standard'
     */
    @Test
    public void standardTest() {
        // TODO: test standard
    }

    /**
     * Test the property 'mac'
     */
    @Test
    public void macTest() {
        // TODO: test mac
    }

    /**
     * Test the property 'ssid'
     */
    @Test
    public void ssidTest() {
        // TODO: test ssid
    }

    /**
     * Test the property 'bssid'
     */
    @Test
    public void bssidTest() {
        // TODO: test bssid
    }

    /**
     * Test the property 'userDefined'
     */
    @Test
    public void userDefinedTest() {
        // TODO: test userDefined
    }

}
