/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.5.0.20211029.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.github.GBSEcom.model.AuthenticationRequest;
import com.github.GBSEcom.model.AuthenticationResult;
import com.github.GBSEcom.model.PaymentTokenPaymentMethod;
import com.github.GBSEcom.model.SplitShipment;
import com.github.GBSEcom.model.StoredCredential;
import com.github.GBSEcom.model.SubMerchantSplit;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PaymentTokenPreAuthTransactionAllOf
 */
public class PaymentTokenPreAuthTransactionAllOfTest {
    private final PaymentTokenPreAuthTransactionAllOf model = new PaymentTokenPreAuthTransactionAllOf();

    /**
     * Model tests for PaymentTokenPreAuthTransactionAllOf
     */
    @Test
    public void testPaymentTokenPreAuthTransactionAllOf() {
        // TODO: test PaymentTokenPreAuthTransactionAllOf
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'storedCredentials'
     */
    @Test
    public void storedCredentialsTest() {
        // TODO: test storedCredentials
    }

    /**
     * Test the property 'splitShipment'
     */
    @Test
    public void splitShipmentTest() {
        // TODO: test splitShipment
    }

    /**
     * Test the property 'settlementSplit'
     */
    @Test
    public void settlementSplitTest() {
        // TODO: test settlementSplit
    }

    /**
     * Test the property 'authenticationRequest'
     */
    @Test
    public void authenticationRequestTest() {
        // TODO: test authenticationRequest
    }

    /**
     * Test the property 'authenticationResult'
     */
    @Test
    public void authenticationResultTest() {
        // TODO: test authenticationResult
    }

    /**
     * Test the property 'decrementalFlag'
     */
    @Test
    public void decrementalFlagTest() {
        // TODO: test decrementalFlag
    }

}
