/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.11.0.20200423.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.github.GBSEcom.model.SubMerchantData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PaymentFacilitator
 */
public class PaymentFacilitatorTest {
    private final PaymentFacilitator model = new PaymentFacilitator();

    /**
     * Model tests for PaymentFacilitator
     */
    @Test
    public void testPaymentFacilitator() {
        // TODO: test PaymentFacilitator
    }

    /**
     * Test the property 'externalMerchantId'
     */
    @Test
    public void externalMerchantIdTest() {
        // TODO: test externalMerchantId
    }

    /**
     * Test the property 'paymentFacilitatorId'
     */
    @Test
    public void paymentFacilitatorIdTest() {
        // TODO: test paymentFacilitatorId
    }

    /**
     * Test the property 'saleOrganizationId'
     */
    @Test
    public void saleOrganizationIdTest() {
        // TODO: test saleOrganizationId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'subMerchantData'
     */
    @Test
    public void subMerchantDataTest() {
        // TODO: test subMerchantData
    }

}
