/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.14.0.20201015.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.github.GBSEcom.model.AdditionalAmountRate;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PurchaseCardsLevel3LineItems
 */
public class PurchaseCardsLevel3LineItemsTest {
    private final PurchaseCardsLevel3LineItems model = new PurchaseCardsLevel3LineItems();

    /**
     * Model tests for PurchaseCardsLevel3LineItems
     */
    @Test
    public void testPurchaseCardsLevel3LineItems() {
        // TODO: test PurchaseCardsLevel3LineItems
    }

    /**
     * Test the property 'commodityCode'
     */
    @Test
    public void commodityCodeTest() {
        // TODO: test commodityCode
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'unitMeasure'
     */
    @Test
    public void unitMeasureTest() {
        // TODO: test unitMeasure
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'vatAmountAndRate'
     */
    @Test
    public void vatAmountAndRateTest() {
        // TODO: test vatAmountAndRate
    }

    /**
     * Test the property 'discountAmountAndRate'
     */
    @Test
    public void discountAmountAndRateTest() {
        // TODO: test discountAmountAndRate
    }

    /**
     * Test the property 'lineItemTotal'
     */
    @Test
    public void lineItemTotalTest() {
        // TODO: test lineItemTotal
    }

}
