/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.11.0.20200423.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import com.github.GBSEcom.model.AdditionalAmountRate;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PurchaseCardsLevel2
 */
public class PurchaseCardsLevel2Test {
    private final PurchaseCardsLevel2 model = new PurchaseCardsLevel2();

    /**
     * Model tests for PurchaseCardsLevel2
     */
    @Test
    public void testPurchaseCardsLevel2() {
        // TODO: test PurchaseCardsLevel2
    }

    /**
     * Test the property 'customerReferenceID'
     */
    @Test
    public void customerReferenceIDTest() {
        // TODO: test customerReferenceID
    }

    /**
     * Test the property 'supplierInvoiceNumber'
     */
    @Test
    public void supplierInvoiceNumberTest() {
        // TODO: test supplierInvoiceNumber
    }

    /**
     * Test the property 'supplierVATRegistrationNumber'
     */
    @Test
    public void supplierVATRegistrationNumberTest() {
        // TODO: test supplierVATRegistrationNumber
    }

    /**
     * Test the property 'totalDiscountAmountAndRate'
     */
    @Test
    public void totalDiscountAmountAndRateTest() {
        // TODO: test totalDiscountAmountAndRate
    }

    /**
     * Test the property 'vatShippingAmountAndRate'
     */
    @Test
    public void vatShippingAmountAndRateTest() {
        // TODO: test vatShippingAmountAndRate
    }

}
