/*
 * First Data REST Payment API Specification
 * First Data REST API for payment features for 6.2.0 release
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.firstdata.apiclient.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Amount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T17:00:16.359-05:00")
public class Amount {
    @SerializedName("total")
    private BigDecimal total = null;

    @SerializedName("currency")
    private String currency = null;

    @SerializedName("components")
    private AmountComponents components = null;

    public Amount total(BigDecimal total) {
        this.total = total;
        return this;
    }

    /**
     * Get total
     *
     * @return total
     **/
    @ApiModelProperty(example = "100.24", required = true, value = "")
    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public Amount currency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * ISO 4217 (http://en.wikipedia.org/wiki/ISO_4217) currency code.
     *
     * @return currency
     **/
    @ApiModelProperty(example = "EUR", required = true, value = "ISO 4217 (http://en.wikipedia.org/wiki/ISO_4217) currency code.")
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Amount components(AmountComponents components) {
        this.components = components;
        return this;
    }

    /**
     * Get components
     *
     * @return components
     **/
    @ApiModelProperty(value = "")
    public AmountComponents getComponents() {
        return components;
    }

    public void setComponents(AmountComponents components) {
        this.components = components;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Amount amount = (Amount) o;
        return Objects.equals(this.total, amount.total) &&
                Objects.equals(this.currency, amount.currency) &&
                Objects.equals(this.components, amount.components);
    }

    @Override
    public int hashCode() {
        return Objects.hash(total, currency, components);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Amount {\n");

        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("    components: ").append(toIndentedString(components)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

