/*
 * First Data REST Payment API Specification
 * First Data REST API for payment features for 6.2.0 release
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.firstdata.apiclient.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Additional data specific to the lodging industry
 */
@ApiModel(description = "Additional data specific to the lodging industry")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T17:00:16.359-05:00")
public class Lodging {
    @SerializedName("arrivalDate")
    private LocalDate arrivalDate = null;

    @SerializedName("departureDate")
    private LocalDate departureDate = null;

    @SerializedName("folioNumber")
    private String folioNumber = null;

    @SerializedName("extraCharges")
    private List<LodgingExtraCharges> extraCharges = null;

    @SerializedName("noShowIndicator")
    private Boolean noShowIndicator = null;

    public Lodging arrivalDate(LocalDate arrivalDate) {
        this.arrivalDate = arrivalDate;
        return this;
    }

    /**
     * Date of arrival
     *
     * @return arrivalDate
     **/
    @ApiModelProperty(example = "2010-05-15", value = "Date of arrival")
    public LocalDate getArrivalDate() {
        return arrivalDate;
    }

    public void setArrivalDate(LocalDate arrivalDate) {
        this.arrivalDate = arrivalDate;
    }

    public Lodging departureDate(LocalDate departureDate) {
        this.departureDate = departureDate;
        return this;
    }

    /**
     * Date of departure
     *
     * @return departureDate
     **/
    @ApiModelProperty(example = "2018-01-28", value = "Date of departure")
    public LocalDate getDepartureDate() {
        return departureDate;
    }

    public void setDepartureDate(LocalDate departureDate) {
        this.departureDate = departureDate;
    }

    public Lodging folioNumber(String folioNumber) {
        this.folioNumber = folioNumber;
        return this;
    }

    /**
     * Portfolio number
     *
     * @return folioNumber
     **/
    @ApiModelProperty(value = "Portfolio number")
    public String getFolioNumber() {
        return folioNumber;
    }

    public void setFolioNumber(String folioNumber) {
        this.folioNumber = folioNumber;
    }

    public Lodging extraCharges(List<LodgingExtraCharges> extraCharges) {
        this.extraCharges = extraCharges;
        return this;
    }

    public Lodging addExtraChargesItem(LodgingExtraCharges extraChargesItem) {
        if (this.extraCharges == null) {
            this.extraCharges = new ArrayList<>();
        }
        this.extraCharges.add(extraChargesItem);
        return this;
    }

    /**
     * Get extraCharges
     *
     * @return extraCharges
     **/
    @ApiModelProperty(value = "")
    public List<LodgingExtraCharges> getExtraCharges() {
        return extraCharges;
    }

    public void setExtraCharges(List<LodgingExtraCharges> extraCharges) {
        this.extraCharges = extraCharges;
    }

    public Lodging noShowIndicator(Boolean noShowIndicator) {
        this.noShowIndicator = noShowIndicator;
        return this;
    }

    /**
     * Get noShowIndicator
     *
     * @return noShowIndicator
     **/
    @ApiModelProperty(value = "")
    public Boolean isNoShowIndicator() {
        return noShowIndicator;
    }

    public void setNoShowIndicator(Boolean noShowIndicator) {
        this.noShowIndicator = noShowIndicator;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Lodging lodging = (Lodging) o;
        return Objects.equals(this.arrivalDate, lodging.arrivalDate) &&
                Objects.equals(this.departureDate, lodging.departureDate) &&
                Objects.equals(this.folioNumber, lodging.folioNumber) &&
                Objects.equals(this.extraCharges, lodging.extraCharges) &&
                Objects.equals(this.noShowIndicator, lodging.noShowIndicator);
    }

    @Override
    public int hashCode() {
        return Objects.hash(arrivalDate, departureDate, folioNumber, extraCharges, noShowIndicator);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Lodging {\n");

        sb.append("    arrivalDate: ").append(toIndentedString(arrivalDate)).append("\n");
        sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
        sb.append("    folioNumber: ").append(toIndentedString(folioNumber)).append("\n");
        sb.append("    extraCharges: ").append(toIndentedString(extraCharges)).append("\n");
        sb.append("    noShowIndicator: ").append(toIndentedString(noShowIndicator)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

