/*
 * Payment Gateway API Specification.
 * Payment Gateway API for payment processing. Version 6.4.0.20181018.001 
 *
 * OpenAPI spec version: 6.4.0.20181018.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.GBSEcom.model.Airline;
import com.github.GBSEcom.model.CarRental;
import com.github.GBSEcom.model.Lodging;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Model for Industry Specific information
 */
@ApiModel(description = "Model for Industry Specific information")

public class IndustrySpecificExtensions {
  public static final String SERIALIZED_NAME_AIRLINE = "airline";
  @SerializedName(SERIALIZED_NAME_AIRLINE)
  private Airline airline = null;

  public static final String SERIALIZED_NAME_LODGING = "lodging";
  @SerializedName(SERIALIZED_NAME_LODGING)
  private Lodging lodging = null;

  public static final String SERIALIZED_NAME_CAR_RENTAL = "carRental";
  @SerializedName(SERIALIZED_NAME_CAR_RENTAL)
  private CarRental carRental = null;

  public IndustrySpecificExtensions airline(Airline airline) {
    this.airline = airline;
    return this;
  }

   /**
   * Get airline
   * @return airline
  **/
  @ApiModelProperty(value = "")
  public Airline getAirline() {
    return airline;
  }

  public void setAirline(Airline airline) {
    this.airline = airline;
  }

  public IndustrySpecificExtensions lodging(Lodging lodging) {
    this.lodging = lodging;
    return this;
  }

   /**
   * Get lodging
   * @return lodging
  **/
  @ApiModelProperty(value = "")
  public Lodging getLodging() {
    return lodging;
  }

  public void setLodging(Lodging lodging) {
    this.lodging = lodging;
  }

  public IndustrySpecificExtensions carRental(CarRental carRental) {
    this.carRental = carRental;
    return this;
  }

   /**
   * Get carRental
   * @return carRental
  **/
  @ApiModelProperty(value = "")
  public CarRental getCarRental() {
    return carRental;
  }

  public void setCarRental(CarRental carRental) {
    this.carRental = carRental;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndustrySpecificExtensions industrySpecificExtensions = (IndustrySpecificExtensions) o;
    return Objects.equals(this.airline, industrySpecificExtensions.airline) &&
        Objects.equals(this.lodging, industrySpecificExtensions.lodging) &&
        Objects.equals(this.carRental, industrySpecificExtensions.carRental);
  }

  @Override
  public int hashCode() {
    return Objects.hash(airline, lodging, carRental);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndustrySpecificExtensions {\n");
    
    sb.append("    airline: ").append(toIndentedString(airline)).append("\n");
    sb.append("    lodging: ").append(toIndentedString(lodging)).append("\n");
    sb.append("    carRental: ").append(toIndentedString(carRental)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

