/*
 * Payment Gateway API Specification.
 * Payment Gateway API for payment processing. Version 6.4.0.20181018.001 
 *
 * OpenAPI spec version: 6.4.0.20181018.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.GBSEcom.model.Dcc;
import com.github.GBSEcom.model.InstallmentOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PrimaryTransactionAdditionalDetails
 */

public class PrimaryTransactionAdditionalDetails {
  public static final String SERIALIZED_NAME_REFERENCE_NUMBER = "referenceNumber";
  @SerializedName(SERIALIZED_NAME_REFERENCE_NUMBER)
  private String referenceNumber;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  public static final String SERIALIZED_NAME_DYNAMIC_MERCHANT_NAME = "dynamicMerchantName";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_MERCHANT_NAME)
  private String dynamicMerchantName;

  public static final String SERIALIZED_NAME_INVOICE_NUMBER = "invoiceNumber";
  @SerializedName(SERIALIZED_NAME_INVOICE_NUMBER)
  private String invoiceNumber;

  public static final String SERIALIZED_NAME_PURCHASE_ORDER_NUMBER = "purchaseOrderNumber";
  @SerializedName(SERIALIZED_NAME_PURCHASE_ORDER_NUMBER)
  private String purchaseOrderNumber;

  public static final String SERIALIZED_NAME_RECURRING_TYPE = "recurringType";
  @SerializedName(SERIALIZED_NAME_RECURRING_TYPE)
  private String recurringType;

  public static final String SERIALIZED_NAME_INSTALLMENT_OPTIONS = "installmentOptions";
  @SerializedName(SERIALIZED_NAME_INSTALLMENT_OPTIONS)
  private InstallmentOptions installmentOptions = null;

  public static final String SERIALIZED_NAME_MCC = "mcc";
  @SerializedName(SERIALIZED_NAME_MCC)
  private String mcc;

  public static final String SERIALIZED_NAME_DCC = "dcc";
  @SerializedName(SERIALIZED_NAME_DCC)
  private Dcc dcc = null;

  public PrimaryTransactionAdditionalDetails referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * For FORCED_TICKET only. Stores the six digit reference number you have received as the result of a successful external authorization (e.g. by phone). The Gateway needs this number for uniquely mapping a ForcedTicket transaction to a previously performed external authorization.] 
   * @return referenceNumber
  **/
  @ApiModelProperty(example = "123455", value = "For FORCED_TICKET only. Stores the six digit reference number you have received as the result of a successful external authorization (e.g. by phone). The Gateway needs this number for uniquely mapping a ForcedTicket transaction to a previously performed external authorization.] ")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public PrimaryTransactionAdditionalDetails comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Comments for the payment
   * @return comments
  **/
  @ApiModelProperty(example = "This is a comment", value = "Comments for the payment")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public PrimaryTransactionAdditionalDetails dynamicMerchantName(String dynamicMerchantName) {
    this.dynamicMerchantName = dynamicMerchantName;
    return this;
  }

   /**
   * The name of sub-merchant for the payment facilitator
   * @return dynamicMerchantName
  **/
  @ApiModelProperty(example = "Hello Fashion LLC", value = "The name of sub-merchant for the payment facilitator")
  public String getDynamicMerchantName() {
    return dynamicMerchantName;
  }

  public void setDynamicMerchantName(String dynamicMerchantName) {
    this.dynamicMerchantName = dynamicMerchantName;
  }

  public PrimaryTransactionAdditionalDetails invoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Invoice number
   * @return invoiceNumber
  **/
  @ApiModelProperty(example = "551294633441", value = "Invoice number")
  public String getInvoiceNumber() {
    return invoiceNumber;
  }

  public void setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }

  public PrimaryTransactionAdditionalDetails purchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
    return this;
  }

   /**
   * Purchase order number
   * @return purchaseOrderNumber
  **/
  @ApiModelProperty(example = "1223456", value = "Purchase order number")
  public String getPurchaseOrderNumber() {
    return purchaseOrderNumber;
  }

  public void setPurchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
  }

  public PrimaryTransactionAdditionalDetails recurringType(String recurringType) {
    this.recurringType = recurringType;
    return this;
  }

   /**
   * Valid values are &#39;FIRST&#39;, &#39;REPEAT&#39; and &#39;STANDING_INSTRUCTION&#39;.
   * @return recurringType
  **/
  @ApiModelProperty(value = "Valid values are 'FIRST', 'REPEAT' and 'STANDING_INSTRUCTION'.")
  public String getRecurringType() {
    return recurringType;
  }

  public void setRecurringType(String recurringType) {
    this.recurringType = recurringType;
  }

  public PrimaryTransactionAdditionalDetails installmentOptions(InstallmentOptions installmentOptions) {
    this.installmentOptions = installmentOptions;
    return this;
  }

   /**
   * Get installmentOptions
   * @return installmentOptions
  **/
  @ApiModelProperty(value = "")
  public InstallmentOptions getInstallmentOptions() {
    return installmentOptions;
  }

  public void setInstallmentOptions(InstallmentOptions installmentOptions) {
    this.installmentOptions = installmentOptions;
  }

  public PrimaryTransactionAdditionalDetails mcc(String mcc) {
    this.mcc = mcc;
    return this;
  }

   /**
   * Use this field to override merchant configured MCC value
   * @return mcc
  **/
  @ApiModelProperty(value = "Use this field to override merchant configured MCC value")
  public String getMcc() {
    return mcc;
  }

  public void setMcc(String mcc) {
    this.mcc = mcc;
  }

  public PrimaryTransactionAdditionalDetails dcc(Dcc dcc) {
    this.dcc = dcc;
    return this;
  }

   /**
   * Get dcc
   * @return dcc
  **/
  @ApiModelProperty(value = "")
  public Dcc getDcc() {
    return dcc;
  }

  public void setDcc(Dcc dcc) {
    this.dcc = dcc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrimaryTransactionAdditionalDetails primaryTransactionAdditionalDetails = (PrimaryTransactionAdditionalDetails) o;
    return Objects.equals(this.referenceNumber, primaryTransactionAdditionalDetails.referenceNumber) &&
        Objects.equals(this.comments, primaryTransactionAdditionalDetails.comments) &&
        Objects.equals(this.dynamicMerchantName, primaryTransactionAdditionalDetails.dynamicMerchantName) &&
        Objects.equals(this.invoiceNumber, primaryTransactionAdditionalDetails.invoiceNumber) &&
        Objects.equals(this.purchaseOrderNumber, primaryTransactionAdditionalDetails.purchaseOrderNumber) &&
        Objects.equals(this.recurringType, primaryTransactionAdditionalDetails.recurringType) &&
        Objects.equals(this.installmentOptions, primaryTransactionAdditionalDetails.installmentOptions) &&
        Objects.equals(this.mcc, primaryTransactionAdditionalDetails.mcc) &&
        Objects.equals(this.dcc, primaryTransactionAdditionalDetails.dcc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceNumber, comments, dynamicMerchantName, invoiceNumber, purchaseOrderNumber, recurringType, installmentOptions, mcc, dcc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrimaryTransactionAdditionalDetails {\n");
    
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    dynamicMerchantName: ").append(toIndentedString(dynamicMerchantName)).append("\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    purchaseOrderNumber: ").append(toIndentedString(purchaseOrderNumber)).append("\n");
    sb.append("    recurringType: ").append(toIndentedString(recurringType)).append("\n");
    sb.append("    installmentOptions: ").append(toIndentedString(installmentOptions)).append("\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("    dcc: ").append(toIndentedString(dcc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

