/*
 * Payment Gateway API Specification.
 * Payment Gateway API for payment processing. Version 6.4.0.20181018.001 
 *
 * OpenAPI spec version: 6.4.0.20181018.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.GBSEcom.model.PaymentTokenization;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ReferencedOrder
 */

public class ReferencedOrder {
  public static final String SERIALIZED_NAME_ORDER_ID = "orderId";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  private String orderId;

  public static final String SERIALIZED_NAME_PAYMENT_TOKENIZATION = "paymentTokenization";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TOKENIZATION)
  private PaymentTokenization paymentTokenization = null;

  public ReferencedOrder orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Use this to retrieve the payment instrument information from an existing Order
   * @return orderId
  **/
  @ApiModelProperty(value = "Use this to retrieve the payment instrument information from an existing Order")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public ReferencedOrder paymentTokenization(PaymentTokenization paymentTokenization) {
    this.paymentTokenization = paymentTokenization;
    return this;
  }

   /**
   * Get paymentTokenization
   * @return paymentTokenization
  **/
  @ApiModelProperty(value = "")
  public PaymentTokenization getPaymentTokenization() {
    return paymentTokenization;
  }

  public void setPaymentTokenization(PaymentTokenization paymentTokenization) {
    this.paymentTokenization = paymentTokenization;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferencedOrder referencedOrder = (ReferencedOrder) o;
    return Objects.equals(this.orderId, referencedOrder.orderId) &&
        Objects.equals(this.paymentTokenization, referencedOrder.paymentTokenization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, paymentTokenization);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferencedOrder {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    paymentTokenization: ").append(toIndentedString(paymentTokenization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

