/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.5.0.20211029.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Secure3D21AuthenticationRequestAllOf
 */

public class Secure3D21AuthenticationRequestAllOf {
  public static final String SERIALIZED_NAME_TERM_U_R_L = "termURL";
  @SerializedName(SERIALIZED_NAME_TERM_U_R_L)
  private String termURL;

  public static final String SERIALIZED_NAME_METHOD_NOTIFICATION_U_R_L = "methodNotificationURL";
  @SerializedName(SERIALIZED_NAME_METHOD_NOTIFICATION_U_R_L)
  private String methodNotificationURL;

  /**
   * Indicates whether or not a challenge should be performed. 01 &#x3D; No preference (You have no preference whether a challenge should be performed. This is the default value) 02 &#x3D; No challenge requested (You prefer that no challenge should be performed) 03 &#x3D; Challenge requested: 3DS Requestor Preference (You prefer that a challenge should be performed) 04 &#x3D; Challenge requested: Mandate (There are local or regional mandates that mean that a challenge must be performed) The following are applicable only for 3DS 2.2 protocol. 05 &#x3D; No challenge requested (transactional risk analysis is already performed) 06 &#x3D; No challenge requested (Data share only) 07 &#x3D; No challenge requested (strong consumer authentication is already performed) 08 &#x3D; No challenge requested (utilise whitelist exemption if no challenge required) 09 &#x3D; Challenge requested (whitelist prompt requested if challenge required) 
   */
  @JsonAdapter(ChallengeIndicatorEnum.Adapter.class)
  public enum ChallengeIndicatorEnum {
    _01("01"),
    
    _02("02"),
    
    _03("03"),
    
    _04("04"),
    
    _05("05"),
    
    _06("06"),
    
    _07("07"),
    
    _08("08"),
    
    _09("09");

    private String value;

    ChallengeIndicatorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ChallengeIndicatorEnum fromValue(String value) {
      for (ChallengeIndicatorEnum b : ChallengeIndicatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ChallengeIndicatorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ChallengeIndicatorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ChallengeIndicatorEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ChallengeIndicatorEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CHALLENGE_INDICATOR = "challengeIndicator";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_INDICATOR)
  private ChallengeIndicatorEnum challengeIndicator = ChallengeIndicatorEnum._01;

  /**
   * Defines the size of the challenge window displayed to customers during authentication. 01 &#x3D; 250 x 400 02 &#x3D; 390 x 400 03 &#x3D; 500 x 600 04 &#x3D; 600 x 400 05 &#x3D; Full screen 
   */
  @JsonAdapter(ChallengeWindowSizeEnum.Adapter.class)
  public enum ChallengeWindowSizeEnum {
    _01("01"),
    
    _02("02"),
    
    _03("03"),
    
    _04("04"),
    
    _05("05");

    private String value;

    ChallengeWindowSizeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ChallengeWindowSizeEnum fromValue(String value) {
      for (ChallengeWindowSizeEnum b : ChallengeWindowSizeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ChallengeWindowSizeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ChallengeWindowSizeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ChallengeWindowSizeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ChallengeWindowSizeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CHALLENGE_WINDOW_SIZE = "challengeWindowSize";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_WINDOW_SIZE)
  private ChallengeWindowSizeEnum challengeWindowSize;

  public static final String SERIALIZED_NAME_BROWSER_JAVA_SCRIPT_ENABLED = "browserJavaScriptEnabled";
  @SerializedName(SERIALIZED_NAME_BROWSER_JAVA_SCRIPT_ENABLED)
  private Boolean browserJavaScriptEnabled;

  /**
   * Provides additional information to the ACS to determine the best approach for handling an authentication request. 01 &#x3D; Payment transaction 02 &#x3D; Recurring transaction 03 &#x3D; Installment transaction 04 &#x3D; Add card 05 &#x3D; Maintain card 06 &#x3D; Card holder verification as part of EMV token ID and Value 
   */
  @JsonAdapter(AuthenticationIndicatorEnum.Adapter.class)
  public enum AuthenticationIndicatorEnum {
    _01("01"),
    
    _02("02"),
    
    _03("03"),
    
    _04("04"),
    
    _05("05"),
    
    _06("06");

    private String value;

    AuthenticationIndicatorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AuthenticationIndicatorEnum fromValue(String value) {
      for (AuthenticationIndicatorEnum b : AuthenticationIndicatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AuthenticationIndicatorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AuthenticationIndicatorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AuthenticationIndicatorEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AuthenticationIndicatorEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AUTHENTICATION_INDICATOR = "authenticationIndicator";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_INDICATOR)
  private AuthenticationIndicatorEnum authenticationIndicator = AuthenticationIndicatorEnum._01;

  /**
   * 02 &#x3D; BRW 03 &#x3D; 3RI 
   */
  @JsonAdapter(Secure3DDeviceChannelEnum.Adapter.class)
  public enum Secure3DDeviceChannelEnum {
    _02("02"),
    
    _03("03");

    private String value;

    Secure3DDeviceChannelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static Secure3DDeviceChannelEnum fromValue(String value) {
      for (Secure3DDeviceChannelEnum b : Secure3DDeviceChannelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<Secure3DDeviceChannelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final Secure3DDeviceChannelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public Secure3DDeviceChannelEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return Secure3DDeviceChannelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SECURE3_D_DEVICE_CHANNEL = "secure3DDeviceChannel";
  @SerializedName(SERIALIZED_NAME_SECURE3_D_DEVICE_CHANNEL)
  private Secure3DDeviceChannelEnum secure3DDeviceChannel;

  /**
   * 01 &#x3D; Recurring transaction 02 &#x3D; Instalment transaction 03 &#x3D; Add card 04 &#x3D; Maintain card information 05 &#x3D; Account verification 06 &#x3D; Split/delayed shipment 07 &#x3D; Top-up 08 &#x3D; Mail Order 09 &#x3D; Telephone Order 10 &#x3D; Whitelist status check 11 &#x3D; Other payment 
   */
  @JsonAdapter(Secure3DThreeRIIndicatorEnum.Adapter.class)
  public enum Secure3DThreeRIIndicatorEnum {
    _01("01"),
    
    _02("02"),
    
    _03("03"),
    
    _04("04"),
    
    _05("05"),
    
    _06("06"),
    
    _07("07"),
    
    _08("08"),
    
    _09("09"),
    
    _10("10"),
    
    _11("11");

    private String value;

    Secure3DThreeRIIndicatorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static Secure3DThreeRIIndicatorEnum fromValue(String value) {
      for (Secure3DThreeRIIndicatorEnum b : Secure3DThreeRIIndicatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<Secure3DThreeRIIndicatorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final Secure3DThreeRIIndicatorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public Secure3DThreeRIIndicatorEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return Secure3DThreeRIIndicatorEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SECURE3_D_THREE_R_I_INDICATOR = "secure3DThreeRIIndicator";
  @SerializedName(SERIALIZED_NAME_SECURE3_D_THREE_R_I_INDICATOR)
  private Secure3DThreeRIIndicatorEnum secure3DThreeRIIndicator;

  public static final String SERIALIZED_NAME_RECURRING_EXPIRY = "recurringExpiry";
  @SerializedName(SERIALIZED_NAME_RECURRING_EXPIRY)
  private String recurringExpiry;

  public static final String SERIALIZED_NAME_RECURRING_FREQUENCY = "recurringFrequency";
  @SerializedName(SERIALIZED_NAME_RECURRING_FREQUENCY)
  private Integer recurringFrequency;


  public Secure3D21AuthenticationRequestAllOf termURL(String termURL) {
    
    this.termURL = termURL;
    return this;
  }

   /**
   * The result of the authentication will be sent to this URL. If not provided, a term URL will be dynamically generated. Note this must be a valid URL (special characters should be URL-encoded).
   * @return termURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://www.mywebshop.com/process3dSecure", value = "The result of the authentication will be sent to this URL. If not provided, a term URL will be dynamically generated. Note this must be a valid URL (special characters should be URL-encoded).")

  public String getTermURL() {
    return termURL;
  }



  public void setTermURL(String termURL) {
    this.termURL = termURL;
  }


  public Secure3D21AuthenticationRequestAllOf methodNotificationURL(String methodNotificationURL) {
    
    this.methodNotificationURL = methodNotificationURL;
    return this;
  }

   /**
   * The 3DS method iframe and transaction ID will be sent here. Note this must be a valid URL (special characters should be URL-encoded).
   * @return methodNotificationURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://www.mywebshop.com/process3dSecureMethodNotification?transactionReferenceNumber=ffffffff-ba0b-539f-8000-016b2343ad7e", value = "The 3DS method iframe and transaction ID will be sent here. Note this must be a valid URL (special characters should be URL-encoded).")

  public String getMethodNotificationURL() {
    return methodNotificationURL;
  }



  public void setMethodNotificationURL(String methodNotificationURL) {
    this.methodNotificationURL = methodNotificationURL;
  }


  public Secure3D21AuthenticationRequestAllOf challengeIndicator(ChallengeIndicatorEnum challengeIndicator) {
    
    this.challengeIndicator = challengeIndicator;
    return this;
  }

   /**
   * Indicates whether or not a challenge should be performed. 01 &#x3D; No preference (You have no preference whether a challenge should be performed. This is the default value) 02 &#x3D; No challenge requested (You prefer that no challenge should be performed) 03 &#x3D; Challenge requested: 3DS Requestor Preference (You prefer that a challenge should be performed) 04 &#x3D; Challenge requested: Mandate (There are local or regional mandates that mean that a challenge must be performed) The following are applicable only for 3DS 2.2 protocol. 05 &#x3D; No challenge requested (transactional risk analysis is already performed) 06 &#x3D; No challenge requested (Data share only) 07 &#x3D; No challenge requested (strong consumer authentication is already performed) 08 &#x3D; No challenge requested (utilise whitelist exemption if no challenge required) 09 &#x3D; Challenge requested (whitelist prompt requested if challenge required) 
   * @return challengeIndicator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "01", value = "Indicates whether or not a challenge should be performed. 01 = No preference (You have no preference whether a challenge should be performed. This is the default value) 02 = No challenge requested (You prefer that no challenge should be performed) 03 = Challenge requested: 3DS Requestor Preference (You prefer that a challenge should be performed) 04 = Challenge requested: Mandate (There are local or regional mandates that mean that a challenge must be performed) The following are applicable only for 3DS 2.2 protocol. 05 = No challenge requested (transactional risk analysis is already performed) 06 = No challenge requested (Data share only) 07 = No challenge requested (strong consumer authentication is already performed) 08 = No challenge requested (utilise whitelist exemption if no challenge required) 09 = Challenge requested (whitelist prompt requested if challenge required) ")

  public ChallengeIndicatorEnum getChallengeIndicator() {
    return challengeIndicator;
  }



  public void setChallengeIndicator(ChallengeIndicatorEnum challengeIndicator) {
    this.challengeIndicator = challengeIndicator;
  }


  public Secure3D21AuthenticationRequestAllOf challengeWindowSize(ChallengeWindowSizeEnum challengeWindowSize) {
    
    this.challengeWindowSize = challengeWindowSize;
    return this;
  }

   /**
   * Defines the size of the challenge window displayed to customers during authentication. 01 &#x3D; 250 x 400 02 &#x3D; 390 x 400 03 &#x3D; 500 x 600 04 &#x3D; 600 x 400 05 &#x3D; Full screen 
   * @return challengeWindowSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "01", value = "Defines the size of the challenge window displayed to customers during authentication. 01 = 250 x 400 02 = 390 x 400 03 = 500 x 600 04 = 600 x 400 05 = Full screen ")

  public ChallengeWindowSizeEnum getChallengeWindowSize() {
    return challengeWindowSize;
  }



  public void setChallengeWindowSize(ChallengeWindowSizeEnum challengeWindowSize) {
    this.challengeWindowSize = challengeWindowSize;
  }


  public Secure3D21AuthenticationRequestAllOf browserJavaScriptEnabled(Boolean browserJavaScriptEnabled) {
    
    this.browserJavaScriptEnabled = browserJavaScriptEnabled;
    return this;
  }

   /**
   * Indicates if the browser issuing the request is capable of performing JavaScript.
   * @return browserJavaScriptEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if the browser issuing the request is capable of performing JavaScript.")

  public Boolean getBrowserJavaScriptEnabled() {
    return browserJavaScriptEnabled;
  }



  public void setBrowserJavaScriptEnabled(Boolean browserJavaScriptEnabled) {
    this.browserJavaScriptEnabled = browserJavaScriptEnabled;
  }


  public Secure3D21AuthenticationRequestAllOf authenticationIndicator(AuthenticationIndicatorEnum authenticationIndicator) {
    
    this.authenticationIndicator = authenticationIndicator;
    return this;
  }

   /**
   * Provides additional information to the ACS to determine the best approach for handling an authentication request. 01 &#x3D; Payment transaction 02 &#x3D; Recurring transaction 03 &#x3D; Installment transaction 04 &#x3D; Add card 05 &#x3D; Maintain card 06 &#x3D; Card holder verification as part of EMV token ID and Value 
   * @return authenticationIndicator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "01", value = "Provides additional information to the ACS to determine the best approach for handling an authentication request. 01 = Payment transaction 02 = Recurring transaction 03 = Installment transaction 04 = Add card 05 = Maintain card 06 = Card holder verification as part of EMV token ID and Value ")

  public AuthenticationIndicatorEnum getAuthenticationIndicator() {
    return authenticationIndicator;
  }



  public void setAuthenticationIndicator(AuthenticationIndicatorEnum authenticationIndicator) {
    this.authenticationIndicator = authenticationIndicator;
  }


  public Secure3D21AuthenticationRequestAllOf secure3DDeviceChannel(Secure3DDeviceChannelEnum secure3DDeviceChannel) {
    
    this.secure3DDeviceChannel = secure3DDeviceChannel;
    return this;
  }

   /**
   * 02 &#x3D; BRW 03 &#x3D; 3RI 
   * @return secure3DDeviceChannel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "02", value = "02 = BRW 03 = 3RI ")

  public Secure3DDeviceChannelEnum getSecure3DDeviceChannel() {
    return secure3DDeviceChannel;
  }



  public void setSecure3DDeviceChannel(Secure3DDeviceChannelEnum secure3DDeviceChannel) {
    this.secure3DDeviceChannel = secure3DDeviceChannel;
  }


  public Secure3D21AuthenticationRequestAllOf secure3DThreeRIIndicator(Secure3DThreeRIIndicatorEnum secure3DThreeRIIndicator) {
    
    this.secure3DThreeRIIndicator = secure3DThreeRIIndicator;
    return this;
  }

   /**
   * 01 &#x3D; Recurring transaction 02 &#x3D; Instalment transaction 03 &#x3D; Add card 04 &#x3D; Maintain card information 05 &#x3D; Account verification 06 &#x3D; Split/delayed shipment 07 &#x3D; Top-up 08 &#x3D; Mail Order 09 &#x3D; Telephone Order 10 &#x3D; Whitelist status check 11 &#x3D; Other payment 
   * @return secure3DThreeRIIndicator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "01", value = "01 = Recurring transaction 02 = Instalment transaction 03 = Add card 04 = Maintain card information 05 = Account verification 06 = Split/delayed shipment 07 = Top-up 08 = Mail Order 09 = Telephone Order 10 = Whitelist status check 11 = Other payment ")

  public Secure3DThreeRIIndicatorEnum getSecure3DThreeRIIndicator() {
    return secure3DThreeRIIndicator;
  }



  public void setSecure3DThreeRIIndicator(Secure3DThreeRIIndicatorEnum secure3DThreeRIIndicator) {
    this.secure3DThreeRIIndicator = secure3DThreeRIIndicator;
  }


  public Secure3D21AuthenticationRequestAllOf recurringExpiry(String recurringExpiry) {
    
    this.recurringExpiry = recurringExpiry;
    return this;
  }

   /**
   * Date after which no further authorisations shall be performed.
   * @return recurringExpiry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20210819", value = "Date after which no further authorisations shall be performed.")

  public String getRecurringExpiry() {
    return recurringExpiry;
  }



  public void setRecurringExpiry(String recurringExpiry) {
    this.recurringExpiry = recurringExpiry;
  }


  public Secure3D21AuthenticationRequestAllOf recurringFrequency(Integer recurringFrequency) {
    
    this.recurringFrequency = recurringFrequency;
    return this;
  }

   /**
   * Indicates the minimum number of days between authorisations.
   * minimum: 1
   * maximum: 9999
   * @return recurringFrequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "30", value = "Indicates the minimum number of days between authorisations.")

  public Integer getRecurringFrequency() {
    return recurringFrequency;
  }



  public void setRecurringFrequency(Integer recurringFrequency) {
    this.recurringFrequency = recurringFrequency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Secure3D21AuthenticationRequestAllOf secure3D21AuthenticationRequestAllOf = (Secure3D21AuthenticationRequestAllOf) o;
    return Objects.equals(this.termURL, secure3D21AuthenticationRequestAllOf.termURL) &&
        Objects.equals(this.methodNotificationURL, secure3D21AuthenticationRequestAllOf.methodNotificationURL) &&
        Objects.equals(this.challengeIndicator, secure3D21AuthenticationRequestAllOf.challengeIndicator) &&
        Objects.equals(this.challengeWindowSize, secure3D21AuthenticationRequestAllOf.challengeWindowSize) &&
        Objects.equals(this.browserJavaScriptEnabled, secure3D21AuthenticationRequestAllOf.browserJavaScriptEnabled) &&
        Objects.equals(this.authenticationIndicator, secure3D21AuthenticationRequestAllOf.authenticationIndicator) &&
        Objects.equals(this.secure3DDeviceChannel, secure3D21AuthenticationRequestAllOf.secure3DDeviceChannel) &&
        Objects.equals(this.secure3DThreeRIIndicator, secure3D21AuthenticationRequestAllOf.secure3DThreeRIIndicator) &&
        Objects.equals(this.recurringExpiry, secure3D21AuthenticationRequestAllOf.recurringExpiry) &&
        Objects.equals(this.recurringFrequency, secure3D21AuthenticationRequestAllOf.recurringFrequency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(termURL, methodNotificationURL, challengeIndicator, challengeWindowSize, browserJavaScriptEnabled, authenticationIndicator, secure3DDeviceChannel, secure3DThreeRIIndicator, recurringExpiry, recurringFrequency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Secure3D21AuthenticationRequestAllOf {\n");
    sb.append("    termURL: ").append(toIndentedString(termURL)).append("\n");
    sb.append("    methodNotificationURL: ").append(toIndentedString(methodNotificationURL)).append("\n");
    sb.append("    challengeIndicator: ").append(toIndentedString(challengeIndicator)).append("\n");
    sb.append("    challengeWindowSize: ").append(toIndentedString(challengeWindowSize)).append("\n");
    sb.append("    browserJavaScriptEnabled: ").append(toIndentedString(browserJavaScriptEnabled)).append("\n");
    sb.append("    authenticationIndicator: ").append(toIndentedString(authenticationIndicator)).append("\n");
    sb.append("    secure3DDeviceChannel: ").append(toIndentedString(secure3DDeviceChannel)).append("\n");
    sb.append("    secure3DThreeRIIndicator: ").append(toIndentedString(secure3DThreeRIIndicator)).append("\n");
    sb.append("    recurringExpiry: ").append(toIndentedString(recurringExpiry)).append("\n");
    sb.append("    recurringFrequency: ").append(toIndentedString(recurringFrequency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

