/*
 * Payment Gateway API Specification.
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.5.0.20211029.001
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.GBSEcom.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The payment object for SEPA Credit Local Payment.
 */
@ApiModel(description = "The payment object for SEPA Credit Local Payment.")

public class SepaCredit {
  public static final String SERIALIZED_NAME_IBAN = "iban";
  @SerializedName(SERIALIZED_NAME_IBAN)
  private String iban;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public SepaCredit iban(String iban) {
    
    this.iban = iban;
    return this;
  }

   /**
   * Bank account in IBAN format.
   * @return iban
  **/
  @ApiModelProperty(example = "DE34500100600032121604", required = true, value = "Bank account in IBAN format.")

  public String getIban() {
    return iban;
  }



  public void setIban(String iban) {
    this.iban = iban;
  }


  public SepaCredit name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the Account Holder.
   * @return name
  **/
  @ApiModelProperty(example = "John Doe", required = true, value = "The name of the Account Holder.")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SepaCredit sepaCredit = (SepaCredit) o;
    return Objects.equals(this.iban, sepaCredit.iban) &&
        Objects.equals(this.name, sepaCredit.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iban, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SepaCredit {\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

